weights: yolov5s.pt
cfg: /app/yolov5/models/custom_yolov5s.yaml
data: /app/data/yolov5/data.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 10
batch_size: 64
imgsz: 512
rect: false
resume: false
nosave: true
noval: true
noautoanchor: false
evolve: 300
bucket: ''
cache: null
image_weights: false
device: 0,1
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: runs/evolve
name: yolov5s_results
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze: 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/evolve/yolov5s_results3
